logging:
  level: INFO
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 8090
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8091
      bindHost: 127.0.0.1
storageRoot: storageRoot/
credentialsFile: config/credentials
